name: Run Polaris Extract and Upload findings

permissions:
  contents: read
  security-events: write

on:
  schedule:
    - cron: "0 13 * * 1" # Runs every Monday at 13:00 (example schedule, adjust as needed)
  workflow_dispatch:

jobs:
  extract-findings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run extract_findings.py
        env:
          POLARIS_URL: ${{ secrets.POLARIS_URL }}
          POLARIS_TOKEN: ${{ secrets.POLARIS_TOKEN }}
          POLARIS_PORTFOLIO_ID: ${{ secrets.POLARIS_PORTFOLIO_ID }}
          POLARIS_PROJECT_ID: ${{ secrets.POLARIS_PROJECT_ID }}

        run: |
          python .github/tools/extract_findings.py "$POLARIS_URL" "$POLARIS_TOKEN" "$POLARIS_PORTFOLIO_ID" "$POLARIS_PROJECT_ID"

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b5ebac6f4c00c8ccddb7cdcd45fdb248329f808a # v3
        with:
          sarif_file: "polaris_issues.sarif"
